hydra:
  run:
    dir: ./output/logs/${now:%d_%m_%Y}
defaults:
  - _self_
  - secrets: secrets
  - pull_data: pull_data
  - prepare_data: prepare_data
  - do_analysis: do_analysis
  - override hydra/job_logging: logging
