version: 1
formatters:
  simple:
    format: '%(asctime)s - %(filename)s - %(levelname)s - %(message)s'
    datefmt: '%d-%m-%Y %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    filename: ./output/logs/${now:%d_%m_%Y}/${hydra.job.name}.log
    formatter: simple
root:
  handlers: [console, file]

disable_existing_loggers: false
